// X-Wing HPKE parity. Two layers:
//
//  1. Offline KAT (always runs, anywhere): the deterministic seal is stable
//     byte-for-byte and round-trips. Guards the Rust key schedule against
//     regressions without needing a Mac.
//  2. Live CryptoKit interop (runs on macOS 26 with `swift`; skips elsewhere):
//     proves byte-exact interop with Apple's
//     HPKE.Ciphersuite.XWingMLKEM768X25519_SHA256_AES_GCM_256, BOTH
//     directions, via tools/xwing_oracle.swift + the xwing_cli helper.
//     CryptoKit's X-Wing private key is not exportable, so a static
//     "CryptoKit sealed this" vector is impossible; the live oracle is how
//     Apple parity is proven (mirrors the spike).

use std::path::PathBuf;
use std::process::Command;

use sha2::{Digest, Sha256};

use pq_crypto_core::xwing::{
    xwing_open_with_secret, xwing_public_key_from_secret, xwing_seal_deterministic,
    XWING_ENCAPSULATED_KEY_LEN, XWING_PUBLIC_KEY_LEN,
};

// Pinned KAT inputs.
fn kat_secret() -> [u8; 32] {
    [0x07u8; 32]
}
fn kat_randomness() -> [u8; 64] {
    let mut r = [0u8; 64];
    for (i, b) in r.iter_mut().enumerate() {
        *b = i as u8;
    }
    r
}
const KAT_INFO: &[u8] = b"elabify-engage-1|kat-req-0001|commerce";
const KAT_PLAINTEXT: &[u8] = b"maknoon-xwing-hpke-kat:v1";

// Pinned outputs (deterministic; generated by this same code, then frozen).
const KAT_PK_SHA256: &str = "74943b4ecd441ec7f92d22c3fb377a29cd7fb96687efda8fae74ae2219a1c279";
const KAT_ENC_SHA256: &str = "c54f168900711cf524de049d24cf5ba61e8706103877849f9d6e21abceb5dad6";
const KAT_CT_HEX: &str =
    "ef112f183602a6c908b0d9199c58ba3b91ab96ce6f616f9ad1061072461bfde580b8f34ce0fb0ecc28";

fn sha256_hex(b: &[u8]) -> String {
    hex::encode(Sha256::digest(b))
}

#[test]
fn xwing_deterministic_kat_is_stable() {
    let sk = kat_secret();
    let pk = xwing_public_key_from_secret(&sk);
    assert_eq!(pk.len(), XWING_PUBLIC_KEY_LEN);
    assert_eq!(sha256_hex(&pk), KAT_PK_SHA256, "X-Wing pubkey KAT drifted");

    let (enc, ct) =
        xwing_seal_deterministic(&pk, KAT_INFO, KAT_PLAINTEXT, &kat_randomness()).unwrap();
    assert_eq!(enc.len(), XWING_ENCAPSULATED_KEY_LEN);
    assert_eq!(sha256_hex(&enc), KAT_ENC_SHA256, "X-Wing enc KAT drifted");
    assert_eq!(
        hex::encode(&ct),
        KAT_CT_HEX,
        "X-Wing ciphertext KAT drifted"
    );

    let opened = xwing_open_with_secret(&sk, &enc, KAT_INFO, &ct).unwrap();
    assert_eq!(opened, KAT_PLAINTEXT, "round-trip plaintext mismatch");
}

#[test]
fn xwing_open_rejects_wrong_info_and_tamper() {
    let sk = kat_secret();
    let pk = xwing_public_key_from_secret(&sk);
    let (enc, ct) =
        xwing_seal_deterministic(&pk, KAT_INFO, KAT_PLAINTEXT, &kat_randomness()).unwrap();

    // Wrong info -> different key schedule -> AEAD auth fails.
    assert!(
        xwing_open_with_secret(&sk, &enc, b"elabify-engage-1|other|commerce", &ct).is_err(),
        "info binding not enforced"
    );
    // Tampered tag -> AEAD auth fails.
    let mut bad = ct.clone();
    *bad.last_mut().unwrap() ^= 0x01;
    assert!(
        xwing_open_with_secret(&sk, &enc, KAT_INFO, &bad).is_err(),
        "AEAD auth not enforced"
    );
}

// ---- live CryptoKit interop (macOS only) ----

fn oracle_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../tools/xwing_oracle.swift")
}

fn swift_available() -> bool {
    Command::new("swift")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

fn run(cmd: &mut Command) -> Option<String> {
    let out = cmd.output().ok()?;
    if !out.status.success() {
        eprintln!("command failed: {}", String::from_utf8_lossy(&out.stderr));
        return None;
    }
    Some(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

#[test]
fn xwing_interop_with_cryptokit() {
    // CryptoKit is an Apple framework: it exists only on macOS. CI runs on
    // Linux, where the Swift toolchain IS installed (so swift_available() is
    // true) but `import CryptoKit` fails to compile. Gate on the target OS so
    // the live oracle only runs where CryptoKit can.
    if !cfg!(target_os = "macos") {
        eprintln!("SKIP xwing_interop_with_cryptokit: CryptoKit is macOS-only (run on macOS 26)");
        return;
    }
    if !swift_available() || !oracle_path().exists() {
        eprintln!(
            "SKIP xwing_interop_with_cryptokit: swift/CryptoKit not available (run on macOS 26)"
        );
        return;
    }
    let oracle = oracle_path();
    let cli = env!("CARGO_BIN_EXE_xwing_cli");
    let info_hex = hex::encode(b"elabify-engage-1|interop-req-9|commerce");
    let pt = b"{\"presentation\":\"p\",\"payment\":{\"rail\":\"eth\",\"txHash\":\"0xabc\"}}";
    let pt_hex = hex::encode(pt);

    // Direction A (commerce-critical): Rust seals -> CryptoKit opens. Run a
    // few times since each seal uses fresh encapsulation randomness.
    for i in 0..3 {
        let opened = run(Command::new("swift")
            .arg(&oracle)
            .arg("driveRustSeal")
            .arg(cli)
            .arg(&info_hex)
            .arg(&pt_hex))
        .unwrap_or_else(|| panic!("Direction A run {i} produced no output"));
        assert_eq!(
            opened, pt_hex,
            "Direction A mismatch (Rust seal not opened by CryptoKit)"
        );
    }

    // Direction B: CryptoKit seals -> Rust opens.
    let gen = run(Command::new(cli).arg("gen")).expect("xwing_cli gen");
    let (sk_hex, pk_hex) = gen.split_once(' ').expect("gen output");
    let sealed = run(Command::new("swift")
        .arg(&oracle)
        .arg("seal")
        .arg(pk_hex)
        .arg(&info_hex)
        .arg(&pt_hex))
    .expect("CryptoKit seal");
    let (enc_hex, sealed_hex) = sealed.split_once(' ').expect("seal output");
    let opened = run(Command::new(cli)
        .arg("open")
        .arg(sk_hex)
        .arg(&info_hex)
        .arg(enc_hex)
        .arg(sealed_hex))
    .expect("Rust open");
    assert_eq!(
        opened, pt_hex,
        "Direction B mismatch (CryptoKit seal not opened by Rust)"
    );
}
